# Generated by Django 3.1.7 on 2021-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Applicant Name', max_length=1000)),
                ('resume', models.FileField(upload_to='raw')),
            ],
        ),
        migrations.CreateModel(
            name='CSVfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adID', models.IntegerField(default=0)),
                ('csv', models.FileField(upload_to='converted')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='Company Name', max_length=1000)),
                ('title', models.CharField(default='Job Title', max_length=1000)),
                ('description', models.CharField(default='Job Description', max_length=100000)),
            ],
        ),
    ]
